# Generated by Django 4.1.2 on 2022-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/avatar.svg', null=True, upload_to='images/profile_images/'),
        ),
    ]
