# Generated by Django 4.1.2 on 2022-11-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_friendrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="media/images/avatar.svg",
                null=True,
                upload_to="media/images/profile_images/",
            ),
        ),
    ]
